# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master1

pool:
  name: Default
  vmImage: ubuntu-latest
  
stages:
- stage: Build
  displayName: 'Build the Node js application'
  jobs: 
  - job: Buid_test
    displayName: 'Build and test'
     
    steps: 
    - task: NodeTool@0
      inputs:
        versionSpec: '10.x'
      displayName: 'Install Node.js'
    - script: |
        npm install
        npm run build
        npm test
      displayName: 'npm install and build'  
    - task: PublishTestResults@2
      inputs:
       testResultsFormat: 'JUnit'
       testResultsFiles: '**/TEST-*.xml'
      displayName: Publishing test reports  
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(Build.BinariesDirectory)'
        includeRootFolder: true
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true
      displayName: Archieve the file 
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container' 
      displayName: Publish Build artifact

- stage: Production
  displayName: Deploying production
  dependsOn: build
  jobs:
  - deployment: DeployProd    
    displayName: 'deploy prod'
    environment: Production
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureRmWebAppDeployment@4
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'Dev(c308cf65-784f-44a0-bcba-c4f5e93f1454)'
              appType: 'webApp'
              WebAppName: 'nodejsapp6'
              deployToSlotOrASE: true
              ResourceGroupName: 'test'
              SlotName: 'stage'
              packageForLinux: '$(Build.ArtifactStagingDirectory)/*.zip'
            displayName: Deploying application  

          - task: AzureAppServiceManage@0
            inputs:
              azureSubscription: 'Dev(c308cf65-784f-44a0-bcba-c4f5e93f1454)'
              Action: 'Swap Slots'
              WebAppName: 'nodejsapp6'
              ResourceGroupName: 'test'
              SourceSlot: 'stage'
              SwapWithProduction: true
            displayName: Managing the slots  
            
              



         


      


